FROM node:20-alpine

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package.json ./

# Install app dependencies
RUN yarn install

COPY .env.dev .env  

# Bundle app source
COPY . .

# Start the server using the production build
CMD [ "yarn" ,"start:dev" ]
